name: nmt
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.6
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
    - transformers
    - datasets
    - tokenizers
    - sacrebleu
    - accelerate
    - tqdm